version: 2
jobs:
    build:
        docker:
            - image: quepid/es-plugin-test
        steps:
            - checkout
            - run: ./gradlew clean check -Des.insecure.allow.root=true  -Dtests.jvms=1
