version: 2
jobs:
    build:
        docker:
            - image: quepid/es-plugin-test
        steps:
            - checkout
            - run: 
                name: Full ES Plugin Build ('clean and check')
                command: ./gradlew clean check --no-daemon -Dtests.jvms=1

