version: 2
jobs:
    build:
        docker:
            - image: quepid/es-plugin-test
              environment:
                MAX_HEAP_SIZE: 4096m
                HEAP_NEWSIZE: 1024m
        steps:
            - checkout
            - run: 
                name: Full ES Plugin Build ('clean and check')
                environment: 
                   GRADLE_OPTS: -Xmx2048m -Dorg.gradle.daemon=false
                command: ./gradlew clean check --no-daemon -Dtests.jvms=1

